export { ReactComponent as Check } from './check.svg'
export { ReactComponent as Close } from './close.svg'
export { ReactComponent as Copy } from './copy.svg'
export { ReactComponent as Ellipse } from './ellipse.svg'
export { ReactComponent as FileText } from './file-text.svg'
export { ReactComponent as Plus } from './plus.svg'
export { ReactComponent as Spinner } from './spinner.svg'
